name: CI

on:
  push:
    branches: [live]
jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        dotnet: ["7.0.x"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{matrix.dotnet-version}}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{matrix.dotnet-version}}
      - name: Install dependencies
        run: |
          systemctl --user restart triviaroyale.service
          dotnet restore ./TriviaRoyale/Client/TriviaRoyale.Client.csproj
          dotnet restore ./TriviaRoyale/Server/TriviaRoyale.Server.csproj
      - name: Build
        run: dotnet build ./TriviaRoyale/Server/TriviaRoyale.Server.csproj --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./TriviaRoyale/Server/TriviaRoyale.Server.csproj -c Release -o /var/www/slutprojekt
      - name: Restart the app
        run: |
          export XDG_RUNTIME_DIR=/run/user/$(id -u)
          systemctl --user restart triviaroyale.service
